import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "relative h-screen w-screen font-sans antialiased",
            inter.className,
          )}
        >
          <div>
            <nav>
              <NavBar />
            </nav>
            <main className="relative flex h-full flex-col">
              <div className="flex-1 flex-grow">{children}</div>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
